### ISSUE TITLE
Fallback to Array#contains for Ember < 2.5.x

### ISSUE THREAD

**Issue by benoror** [bmeurant/ember-array-contains-helper#42]
Previous versions of Ember (such as 2.5.x) doesn't support `Array#includes`, a fallback should be considered for backwards compatibility

**Comment by bmeurant** [comment]
Sorry, I missed this issue.

This point should be addressed by the inclusion of `ember-runtime-enumerable-includes-polyfill`.

Are you experimenting some specific issue with ember < 2.8 ? Can you try importing this dep ?

Maybe I should consider to add it in `dependencies` instead of `devDependencies`

**Comment by benoror** [comment]
I used in in (dummy app) [this addon](https://github.com/benoror/ember-formly) I'm developing.

I previously had ember 2.5.x and the `{{array-contains value array}}` helper didn't work as expected.

Since it's a small project [I simply upgraded to ember 2.8.x](https://github.com/benoror/ember-formly/commit/5faa8b1eb595611aa7eb4cc625c6663998da195a) and the issue was gone.

I don't know "version-dependant dependencies" are possible, but it might worth creating a note in the README.md at least, thoughts?

**Comment by bmeurant** [comment]
`ember-runtime-enumerable-includes-polyfill` is very small and smart enough to be added as a full dependency. I will do that soon and It will fix any backward compatibility issue.

Thank you very much for pointing this out.

But I'm curious, what browser / javascript version do you use? Because `Array#includes` is natively supported in most browsers, now ...

**Comment by benoror** [comment]
You're right that's weird, I use Chrome 54. You can try reproducing the issue by running the addon app and then removing the [2.8 upgrade commit](https://github.com/benoror/ember-formly/commit/5faa8b1eb595611aa7eb4cc625c6663998da195a).

Let me know, cheers!
